# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AriaCategoryViewController' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Then'
  pod 'Reusable'
  pod 'AriaSwiftyChain', :path => '../../../Pod/AriaSwiftyChain'

  # Pods for AriaCategoryViewController

  target 'AriaCategoryViewControllerTests' do
    # Pods for testing
  end

end
